import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h3>Header</h3>
      </header>
      <main className={styles.main}>
        <div className={styles.description}>
          <h3>test page</h3>
          <p className={styles.test1}>test-1</p>
          <p className={styles.test2}>test-2</p>
          <p className={styles.test3}>test-3</p>
        </div>
      </main>
      <footer>
        <h3>Footer</h3>
      </footer>
    </>
  )
}
